version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm install && npm start"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/easygenerator
    command: sh -c "npm install && npm start:dev"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
